services:
  postgres:
    image: postgres:14.15
    restart: always
    environment:
      - POSTGRES_USER=coffee-shop
      - POSTGRES_PASSWORD=coffee-shop-password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5757:5432'
volumes:
  postgres: